### ISSUE TITLE
VRChat doesn't work with OpenVR Dynamic Resolution

### ISSUE THREAD

**Issue by Crimson-foxGITHUB** [Louka3000/OpenVR-Dynamic-Resolution#15]
The first game I tested with this plugin was VRChat. Using fpsVR's benchmarking tools, the resolution didn't decrease or increase a single time the entire session. Even going from a less demanding world solo to Test Pilots pubs of 20 returned zero difference in resolution, and GPU frametimes also indicated nothing was happening. At 90Hz, frametimes tended to hover around 16ms instead of 11 or 22.5.

P.S. using minGpuTimeThreshold to avoid changing resolution during loading screens actually doesn't work because games use the GPU to load in assets. Framerates can dip as low as half your normal refresh rate during loading screens.

**Comment by Louka3000** [comment]
Is this consistent? Many people including me use it in VRChat (it was made for it). Can you make sure you’re using the default settings and provide any steps to reproduce if possible? Also what headset are you using (if Quest, VD, ALVR or Link)?

VRChat has 2 loading screens, one of which doesn’t use your GPU. The setting was primarly made for the SteamVR void though.

**Comment by Crimson-foxGITHUB** [comment]
Quest 2 via wired Link, GTX 1660 Super 6GB, Ryzen 7 3700X. 

To reproduce:

-Plug the Quest 2 into the computer
-Open up Oculus Link in your headset
-Open up OpenVR-Dynamic-Resolution.exe, which opens SteamVR
-Launch fpsVR's benchmarking window and VRChat
-Go to a hardware-intensive session
-Use the "detect resolution" button in fpsVR to see it return the exact same resolution it gives in Oculus PC's app settings

**Comment by Crimson-foxGITHUB** [comment]
> 100% is the default value. You need to test in-game. Not sure what you mean by it not working? A friend and

 I have been using it all-weekend. It is not gonna change the text but that’s normal.

Did a quick recording of VRChat running using a very demanding avatar, max mirror resolution, it hitting 45FPS yet not lowering the resolution, alwaysReproject=0. Had to split it into two files and put those parts into two separate .zip files because of GitHub limitations, but here you go.

[part1.zip](https://github.com/Louka3000/OpenVR-Dynamic-Resolution/files/11670885/part1.zip)
[part2.zip](https://github.com/Louka3000/OpenVR-Dynamic-Resolution/files/11670886/part2.zip)

**Comment by Louka3000** [comment]
Any update on this?

**Comment by Crimson-foxGITHUB** [comment]
> Any update on this?

Had to deal with IRL stuff the last two days, will be back tomorrow and with videos on 0.2.1.

**Comment by Crimson-foxGITHUB** [comment]
https://github.com/Louka3000/OpenVR-Dynamic-Resolution/assets/61099225/b6e01e05-9a2f-478d-b2fe-9ef172fcf638

FINALLY, it actually works now that reprojection is handled correctly.

**Comment by Louka3000** [comment]
Glad to hear it ^^

It changes the global resolution for simplicity’s sake. I don’t even know how I’d go about changing it per-game, but there’s not really any advantage. In fact, it’d just be more annoying to reset it and debug.
