### ISSUE TITLE
Target gpu frame time should have a manual target, VRC loading screen and purple frame times.

### ISSUE THREAD

**Issue by candygamer-YT** [Louka3000/OpenVR-Dynamic-Resolution#17]
I've always been ok with a little bit of latency and for lower end cards like my 2080 super even running this makes my resolution drop to 60 percent me knowing I can have it at 150% and have an enjoyable experience (even with the latency I'd rather not see pixels)

VRC loading screen does not load anything showing 1.5-2ms gpu latency and bumping up my resolution and killing me on world entry.

Purple frame times or missed frames count also as 0 latency? and proceed to kill me if Iag out making the lag that much worse

Also any gpu stuttering has lows of 1.5ms causing resolution increase post lag spike.
(Lowering resolution durring constant stuttering until frame times are stable could fix this)

Make resolution as low as possible during purple frame times and set loading screens to <110% to increase quality of life!

Also if CPU frame times can be accounted for (optional) that'd be great! (with a target and a min)

**Comment by Louka3000** [comment]
Hi, please check out https://github.com/Louka3000/OpenVR-Dynamic-Resolution#settings-descriptions

You can change `alwaysReproject` to 1, or even `resIncreaseThreshold` and `resDecreaseThreshold` if you want more control.
You can increase `dataAverageSamples` to avoid it reseting your res during lag spikes or just set `resetOnThreshold` to 0 to disable it altogether.

CPU frametime is a bit tricky, I found no way to get it from SteamVR, altho I know Advanced Frame Timing and FPSVR have it. That’s for another issue.
