### ISSUE TITLE
Take CPU Frametime into account

### ISSUE THREAD

**Issue by Louka3000** [Louka3000/OpenVR-Dynamic-Resolution#18]
FPSVR and XSOverlay have ways to get it somehow. Needs some research.

**Comment by Crimson-foxGITHUB** [comment]
I suppose for now a simpler solution could be to check the GPU frametime in reference to the actual FPS and use that to determine if there's a CPU bottleneck. This application works best for changing resolutions relative to **average** GPU frametime(as in VRChat) as opposed to trying to hold a locked FPS because of particle effects spiking the GPU.

**Comment by Louka3000** [comment]
Simpler solution than _what_? The first step is figuring out how to get CPU frametime, which I had already spent an hour on while coding the rest and found nothing.

**Comment by Crimson-foxGITHUB** [comment]
hmmmmmmm…I know fpsVR does have a way to grab the CPU frametime

**Comment by Louka3000** [comment]
Yeah, both FPSVR and XSOverlay do. I’d have to ask them how they did

**Comment by Louka3000** [comment]
Turns out this should be easily doable.

I found this page with nice documentation: https://developer.valvesoftware.com/wiki/SteamVR/Frame_Timing

`	float m_flCompositorRenderCpuMs; // time spent on cpu submitting the above work for this frame`

**Comment by Louka3000** [comment]
Figured it out!

Spoiler: it was not as easy as I thought to figure out.

Explanation (might not be 100% correct, but this is what I'm going with):

You can see the CPU and GPU Frametimes with the SteamVR (Advanced) Frame Timing
![vrmonitor_8il5X6TM0N](https://github.com/Louka3000/OpenVR-Dynamic-Resolution/assets/20461725/91a73caa-b416-45bd-8903-95111a4a1446)

By clicking on Details, we can see what values we have:
![vrmonitor_xvjugoGm06](https://github.com/Louka3000/OpenVR-Dynamic-Resolution/assets/20461725/b7b94e16-67ea-46d3-9ab3-768bd6cbebae)

The 4 values enabled are the only ones important for calculating the CPU time.

From there, the cpu time can be calculated like this (comments indicate which field you can see in the simplified Frame Timing (Details unchecked)):
```cpp
float cpuTime = frameTiming->m_flCompositorRenderCpuMs // Compositor
		+ (frameTiming->m_flNewFrameReadyMs - frameTiming->m_flNewPosesReadyMs) // Application
		+ max(0, frameTiming->m_flWaitGetPosesCalledMs - frameTiming->m_flNewPosesReadyMs); // Late Start
```

Resources:
https://developer.valvesoftware.com/wiki/SteamVR/Frame_Timing
https://www.gdcvault.com/play/1021771/Advanced-VR
https://github.com/ValveSoftware/openvr/issues/518#issuecomment-303220616

**Comment by Louka3000** [comment]
https://github.com/Louka3000/OpenVR-Dynamic-Resolution/commit/d904ae491f6c46615fc7a6bd1dfd05c6f633ec13
