### ISSUE TITLE
Only increase resolution, if there is vram available

### ISSUE THREAD

**Issue by kruemmelbande** [Louka3000/OpenVR-Dynamic-Resolution#21]
Currently, in lighter to render scenes, it will increase my resolution, until i hit the vram limit, at which point, my framerate drops to about 20, and then the resolution drops back to the minimum.

I think it would be helpful, if it was possible to capture vram usage, and if there is lets say more than 95% vram usage, the resolution just does not increase, no matter how little the gpu frametime is.

**Comment by Louka3000** [comment]
Indeed. Will have to look into a way to get VRAM

**Comment by Louka3000** [comment]
Closed by https://github.com/Louka3000/OpenVR-Dynamic-Resolution/pull/23
Sadly no AMD support, but AMD generally has plenty of VRAM anyways. Anyone feel free to re-open if they do need VRAM monitoring on AMD GPUs. 
Thanks @kruemmelbande !
