### ISSUE TITLE
Ovr Dynamic Resolution keeps running after steamvr closes

### ISSUE THREAD

**Issue by kruemmelbande** [Louka3000/OpenVR-Dynamic-Resolution#24]
I think a way to detect the closing of steamvr, or whatever other runtime is currently being used, would be a good thing to implement, so this does not keep running.

**Comment by Louka3000** [comment]
Weird, it closes automatically on my system 🤔

**Comment by kruemmelbande** [comment]
After disableing and re-enableing, it works now
