### ISSUE TITLE
VRAM only mode

### ISSUE THREAD

**Issue by Switch01** [Louka3000/OpenVR-Dynamic-Resolution#27]
Hi, it would be amazing to be able to disable the resolution scaling based on frametimes and only enable VRAM monitoring.

In VRChat often lowering the resolution gives no extra frames (and they are often even below half the target), but it not uncommon for the VRAM to be completely full, which can be fixed by the dynamic resolution.

Thanks!

**Comment by kruemmelbande** [comment]
You could just set your frame rate target to a very large number, and that should in theory give the same results

**Comment by Switch01** [comment]
Yeah, it should work by doing that but there's no setting to set a custom frame rate target yet, i think.

**Comment by Louka3000** [comment]
`alwaysReproject` will double the target frametime.

Alternatively, to set a custom frametime, change `resIncreaseThreshold` and `resDecreaseThreshold`, but you’d have to change `resIncreaseScale` and/or `resDecreaseScale` along with it

**Comment by owlboy** [comment]
I agree that a simple mode toggle/flag for VRAM only would be a fantastic addition.

**Comment by Switch01** [comment]
> `alwaysReproject` will double the target frametime.
> 
> Alternatively, to set a custom frametime, change `resIncreaseThreshold` and `resDecreaseThreshold` (to, for example, 99), but you’d have to set `resIncreaseScale` to 0 along with it.

Sorry for the delayed response, right after i opened this issue i changed my CPU to a Ryzen 5800X3D, so i'm now much more GPU bound than CPU and my fps are much higher. 
But i did manage to test your settings for a bit before that and it would just gradually increase the resolution to very high levels and not really act like a VRAM limiter, i don't know what caused that behaviour.

**Comment by Louka3000** [comment]
@Switch01 Yes, turns out that it the expected result.

I've made a vram-only option but can't test it right now. Feel free to test it and give me feedback on whether it works or not ^^

Make sure to set `vramOnlyMode` to 1 in settings.ini

[OpenVR-Dynamic-Resolution.zip](https://github.com/Louka3000/OpenVR-Dynamic-Resolution/files/13325939/OpenVR-Dynamic-Resolution.zip)

**Comment by Louka3000** [comment]
https://github.com/Louka3000/OpenVR-Dynamic-Resolution/commit/ac167f6d7bcb91426d7396c24a167d4534cad393 and https://github.com/Louka3000/OpenVR-Dynamic-Resolution/commit/d904ae491f6c46615fc7a6bd1dfd05c6f633ec13
