### ISSUE TITLE
Steam Link

### ISSUE THREAD

**Issue by oOflyeyesOo** [Louka3000/OpenVR-Dynamic-Resolution#29]
Will this effect quality when using the new steam link app released now on Quest?

Just wanted to see your thoughts and if there can be any integrations made to streamline the process.

**Comment by Louka3000** [comment]
It will affect supersampling of the image before it is sent to the Quest, so yes.
If you have a bad GPU, it will help with your framerate. If you have a good GPU, it’ll increase image quality (make sure to increase the Steam Link bitrate as well)
